spring:
  config:
    import: nacos:gateway-server.properties
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
        namespace: public
      config:
        server-addr: http://localhost:8848
        username: nacos
        password: nacos
  application:
    name: gateway-server
server:
  port: 9999

nacos-config:
  oauth:
    public-key:
      data-id: publicKey
      group-id: oauth
